@startuml
Title Purchase Flow
actor Customer
participant Merchant
boundary Chexr_receipt
participant PSP
participant Bank


Customer -> Merchant : 1. do purchase
activate Merchant
Merchant -> Chexr_receipt : 2. receipt info
activate Chexr_receipt
Chexr_receipt -> Merchant: 6. Receipt stored
deactivate Chexr_receipt
Merchant -> PSP: 3. Payment clearing
activate PSP
PSP -> Bank: 4. Digital Receipt
activate Bank
Bank -> Chexr_receipt: 5. Cleared card transaction
activate Chexr_receipt
deactivate Chexr_receipt
deactivate Bank
deactivate PSP


Merchant -> Customer: 7. Payment process completed
deactivate Merchant



@enduml
